config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :establishments do
    resources :operating_hours
  end

  resources :dishes, only: %i[index show new create edit update] do
    post 'active', on: :member
    post 'inactive', on: :member

    resources :dish_options, only: %i[index new create edit update]
  end

  resources :drinks, only: %i[index show new create edit update] do
    post 'active', on: :member
    post 'inactive', on: :member

    resources :drink_options, only: %i[index new create edit update]
  end

  resources :search, only: [:index]

  resources :price_history, only: %i[index]

  resources :tags, only: %i[index new create edit update destroy]

  resources :menus

  resources :orders do
    resources :order_dishes, only: %i[new create]
    resources :order_drinks, only: %i[new create]

    post 'in_preparation', on: :member
    post 'canceled', on: :member
    post 'ready', on: :member
    post 'delivered', on: :member
  end

  resources :pre_registrations

  namespace :api do
    namespace :v1 do
      resources :establishments, param: :code, only: [] do
        resources :orders, param: :code, only: %i[index show] do
          member do
            patch :in_preparation
            patch :canceled
            patch :ready
          end
        end
      end
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @establishment = current_user.establishment

    @query = params[:query]

    if @query.present?
      @dishes = @establishment.dishes.where("name LIKE ? OR description LIKE ?", "%#{@query}%", "%#{@query}%")
      @drinks = @establishment.drinks.where("name LIKE ? OR description LIKE ?", "%#{@query}%", "%#{@query}%")
    end
  end
end

app/views/search/index.html.erb
<% if @dishes.present? %>
  <h1 class='title'>Results found: <%= @dishes.count %></h1>

  <ul>
    <% @dishes.each do |dish| %>
      <li>
        <%= link_to dish.name, dish_path(dish.id) %>

        <%= link_to 'Edit', edit_dish_path(dish.id), 
                          id: dom_id(dish, :edit) %>
      </li>
    <% end %>
  </ul>
<% elsif @drinks.present? %>
  <h1 class='title'>Results found: <%= @drinks.count %></h1>

  <ul>
    <% @drinks.each do |drink| %>
      <li>
        <%= link_to drink.name, drink_path(drink.id) %>

        <%= link_to 'Edit', edit_drink_path(drink.id), 
                          id: dom_id(drink, :edit) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No results found</p>
<% end %>