config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :establishments do
    resources :operating_hours
  end

  resources :dishes, only: %i[index show new create edit update] do
    post 'active', on: :member
    post 'inactive', on: :member

    resources :dish_options, only: %i[index new create edit update]
  end

  resources :drinks, only: %i[index show new create edit update] do
    post 'active', on: :member
    post 'inactive', on: :member

    resources :drink_options, only: %i[index new create edit update]
  end

  resources :search, only: [:index]

  resources :price_history, only: %i[index]

  resources :tags, only: %i[index new create edit update destroy]

  resources :menus

  resources :orders do
    resources :order_dishes, only: %i[new create]
    resources :order_drinks, only: %i[new create]

    post 'in_preparation', on: :member
    post 'canceled', on: :member
    post 'ready', on: :member
    post 'delivered', on: :member
  end

  resources :pre_registrations

  namespace :api do
    namespace :v1 do
      resources :establishments, param: :code, only: [] do
        resources :orders, param: :code, only: %i[index show] do
          member do
            patch :in_preparation
            patch :canceled
            patch :ready
          end
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.all
  end
end

app/views/home/index.html.erb
<h1 class='title'><%= Menu.model_name.human(count: 2) %></h1>

<div class='menu-buttons'>
  <%= link_to t('views.new_menu'), new_menu_path, class: 'new-button' %>
  <%= link_to t('views.new_order'), new_order_path, class: 'new-button' %>
</div>

<% if @menus.any? %>
  <% @menus.each do |menu| %>
    <hr>
    <h2><%= link_to menu.name, menu_path(menu.id) %></h2>

    <div class="menu-card">
      <ul class="dish-list">
        <% menu.items.where(type: 'Dish').each do |dish| %>
          <% if dish.present? %>
            <% dish.options.each do |option| %>
              <li><%= "#{dish.name} #{option.description}" %> <%= option.price %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>

      <ul class="drink-list">
        <% menu.items.where(type: 'Drink').each do |drink| %>
          <% if drink.present? %>
            <% drink.options.each do |option| %>
              <li><%= "#{drink.name} #{option.description} #{option.price}" %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>

      <% unless menu.items.present? %>
        <p><%= t('messages.no_item_registered') %></p>
      <% end %>    
    
    <hr>
  <% end %>
<% else %>
  <p><%= t('messages.no_menu_registered') %></p>
<% end %>