config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :establishments do
    resources :operating_hours
  end

  resources :dishes, only: %i[index show new create edit update] do
    post 'active', on: :member
    post 'inactive', on: :member

    resources :dish_options, only: %i[index new create edit update]
  end

  resources :drinks, only: %i[index show new create edit update] do
    post 'active', on: :member
    post 'inactive', on: :member

    resources :drink_options, only: %i[index new create edit update]
  end

  resources :search, only: [:index]

  resources :price_history, only: %i[index]

  resources :tags, only: %i[index new create edit update destroy]

  resources :menus

  resources :orders do
    resources :order_dishes, only: %i[new create]
    resources :order_drinks, only: %i[new create]

    post 'in_preparation', on: :member
    post 'canceled', on: :member
    post 'ready', on: :member
    post 'delivered', on: :member
  end

  resources :pre_registrations

  namespace :api do
    namespace :v1 do
      resources :establishments, param: :code, only: [] do
        resources :orders, param: :code, only: %i[index show] do
          member do
            patch :in_preparation
            patch :canceled
            patch :ready
          end
        end
      end
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :item_tags
  has_many :items, through: :item_tags

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[edit update]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path, notice: t('notices.tag.registered')
    else
      flash.now.alert = t('alerts.tag.register_fail')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @tag.update(tag_params)
      redirect_to tags_path, notice: t('notices.tag.updated')
    else
      flash.now.alert = t('alerts.tag.update_fail')
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_tag
    @tag = Tag.find_by(id: params[:id])

    if @tag.nil?
      redirect_to tags_path, alert: 'Not found or access not authorized'
    end
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_form.html.erb
<%= form_with model: @tag, local: true do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div><%= f.submit class: 'submit-button' %></div>
<% end %>

app/views/tags/edit.html.erb
<h1 class='title'><%= "#{t('actions.edit')} #{@tag.name}" %></h1>

<% if @tag.errors.any? %>
  <ul>
    <% @tag.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/tags/index.html.erb
<h1 class='title'><%= Tag.model_name.human(count: 2) %></h1>

<div><%= link_to t('views.new_tag'), new_tag_path, class: 'new-button' %></div>

<% if @tags.any? %>
  <table class='table-container'>
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.tag.name') %></th>
        <th><%= t('views.action') %></th>
      </tr>
    </thead>
    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td>
            <%= link_to t('actions.edit'), edit_tag_path(tag.id), 
                id: dom_id(tag, :edit), class: 'edit-button' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are no registered tags</p>
<% end %>

app/views/tags/new.html.erb
<h1 class='title'><%= t('views.new_tag') %></h1>

<% if @tag.errors.any? %>
  <ul>
    <% @tag.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>