config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :establishments do
    resources :operating_hours
  end

  resources :dishes, only: %i[index show new create edit update] do
    post 'active', on: :member
    post 'inactive', on: :member

    resources :dish_options, only: %i[index new create edit update]
  end

  resources :drinks, only: %i[index show new create edit update] do
    post 'active', on: :member
    post 'inactive', on: :member

    resources :drink_options, only: %i[index new create edit update]
  end

  resources :search, only: [:index]

  resources :price_history, only: %i[index]

  resources :tags, only: %i[index new create edit update destroy]

  resources :menus

  resources :orders do
    resources :order_dishes, only: %i[new create]
    resources :order_drinks, only: %i[new create]

    post 'in_preparation', on: :member
    post 'canceled', on: :member
    post 'ready', on: :member
    post 'delivered', on: :member
  end

  resources :pre_registrations

  namespace :api do
    namespace :v1 do
      resources :establishments, param: :code, only: [] do
        resources :orders, param: :code, only: %i[index show] do
          member do
            patch :in_preparation
            patch :canceled
            patch :ready
          end
        end
      end
    end
  end
end

app/models/establishment.rb
class Establishment < ApplicationRecord
  has_many :users
  has_many :operating_hours
  has_many :items, dependent: :destroy
  has_many :dishes, -> { where(type: 'Dish') }, class_name: 'Item'
  has_many :drinks, -> { where(type: 'Drink') }, class_name: 'Item'
  has_many :menus
  has_many :orders
  has_many :pre_registrations

  validates :corporate_name, :brand_name, :cnpj, :address, :number, :neighborhood, :city, :state, :zip_code,
            :phone_number, :email, :code, presence: true
  validates :cnpj, uniqueness: true
  validate :valid_cnpj
  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+(com|br|org)\z/, message: 'must be a valid email' }
  validates :phone_number, length: { in: 10..11, message: 'must be 10 or 11 digits' }

  before_validation :generate_code, on: :create

  after_create :assign_to_admin

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(6).upcase
  end

  def valid_cnpj
    unless CNPJ.valid?(cnpj)
      errors.add(:cnpj, 'is not valid')
    end
  end

  def assign_to_admin
    admin_without_establishment = User.admin.find_by(establishment: nil)
    admin_without_establishment.update(establishment: self) if admin_without_establishment
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :authorize_admin!, only: %i[new create]
  before_action :set_establishment_and_check_user, only: %i[show]
  before_action :check_user_establishment, only: %i[new create]

  def index
    @establishment = current_user.establishment

    if @establishment.nil?
      return redirect_to new_establishment_path, alert: 'Please register an establishment'
    end

    @operating_hours = @establishment.operating_hours.order(:day_of_week)
  end

  def show
  end

  def new
    @establishment = Establishment.new
  end

  def create
    @establishment = current_user.build_establishment(establishment_params)

    if @establishment.save
      current_user.update(establishment: @establishment)
      redirect_to establishment_path(@establishment), notice: t('notices.establishment.registered')
    else
      flash.now.alert = t('alerts.establishment.register_fail')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_establishment_and_check_user
    @establishment = Establishment.find_by(id: params[:id])

    if @establishment.nil? || !@establishment.users.include?(current_user)
      return redirect_to establishments_path, alert: 'Establishment not found or you do not have access'
    end
  end

  def check_user_establishment
    if current_user.establishment.present?
      return redirect_to establishments_path, alert: 'You already have an establishment'
    end
  end

  def establishment_params
    params.require(:establishment).permit(:corporate_name, :brand_name, :cnpj, :address, :number, :neighborhood,
                                          :city, :state, :zip_code, :phone_number, :email, :code)
  end
end

app/views/establishments/_form.html.erb
<%= form_with model: @establishment do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>
  <div>
    <%= f.label :neighborhood %>
    <%= f.text_field :neighborhood %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code, placeholder: '00000000', pattern: "[0-9]*", inputmode: "numeric",
                      maxlength: 9, title: 'Only numbers are allowed' %>
  </div>
  <div>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, placeholder: '00000000000', pattern: "[0-9]*", inputmode: "numeric",
                      maxlength: 11, title: 'Only numbers are allowed' %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/establishments/index.html.erb
<h1 class='title'><%= link_to @establishment.corporate_name, establishment_path(@establishment.id) %></h1>

<hr>

<h2 class='subtitle'><%= OperatingHour.model_name.human(count: 2) %> </h2>

<% if current_user.admin? %>
  <div><%= link_to t('views.new_operating_hour'), new_establishment_operating_hour_path(@establishment.id), class: 'new-button' %></div>
<% end %>

<div class='table-container'>
  <% if @operating_hours.any? %>
    <table>
      <thead>      
        <tr>
          <th><%= t('activerecord.attributes.operating_hour.day_of_week') %></th>
          <th><%= OperatingHour.model_name.human(count: 1) %></th>
          <th><%= t('activerecord.attributes.operating_hour.status') %></th>
        </tr>           
      </thead>
      <tbody>
        <% @operating_hours.each do |oh| %>
          <tr>
            <td>
              <%= link_to oh.translated_day_of_week, 
                  establishment_operating_hour_path(@establishment.id, oh.id), class: 'day-link' %>
            </td>
            <td>
              <%= oh.opening_time.strftime("%H:%M") %> - <%= oh.closing_time.strftime("%H:%M") %>
            </td>
            <td><%= oh.translated_status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p><%= t('messages.no_operating_hour_registered') %></p>
  <% end %>
</div>

app/views/establishments/new.html.erb
<h1 class='title'>Please register your establishment</h1>

<% if @establishment.errors.any? %>
  <ul>
    <% @establishment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/establishments/show.html.erb
<h1 class='title'><%=t('views.my_establishment') %></h1>

<section class='establishment'>
  <div><strong><%= t('activerecord.attributes.establishment.code') %>:</strong> <%= @establishment.code %></div>
  <div><strong><%= t('activerecord.attributes.establishment.corporate_name') %>:</strong> <%= @establishment.corporate_name %></div>
  <div><strong><%= t('activerecord.attributes.establishment.brand_name') %>:</strong> <%= @establishment.brand_name %></div>
  <div><strong>CNPJ:</strong> <%= @establishment.cnpj %></div>
  <div>
    <strong><%= t('views.full_address') %>:</strong> <%= @establishment.address %>, <%= @establishment.number %> - 
                  <%= @establishment.neighborhood %> - <%= @establishment.city %> -
                  <%= @establishment.state %> - <%= t('activerecord.attributes.establishment.zip_code') %>: <%= @establishment.zip_code %>
  </div>
  <div><strong><%= t('activerecord.attributes.establishment.phone_number') %>:</strong> <%= @establishment.phone_number %></div>
  <div><strong>Email:</strong> <%= @establishment.email %></div>
</section>